[project]
authors = ["Grigore-Gabriel Trifan"]
entry = "market.sw"
license = "Apache-2.0"
name = "fuelcast-contracts"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.2" }